spring:
  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}

server:
  port: ${server_port}

config:
  storage_directory: ${files_storage_directory}
  rabbitmq:
    receive_queue: ${receive_file_queue_name}
    document_list_queue_name: ${document_list_queue_name}
    document_queue_name: ${document_queue_name}
    filename_header_name: ${filename_header_name}
    chat_id_header_name: ${chat_id_header_name}
